apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garbo-prod

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/klimatbyran/garbo
    newName: ghcr.io/klimatbyran/garbo # {"$imagepolicy": "flux-system:garbo:name"}
    newTag: 3.1.18 # {"$imagepolicy": "flux-system:garbo:tag"}
