apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garbo

resources:
  - worker.yaml
  - api.yaml
  - ingress.yaml
  - nlm-ingestor.yaml
  - service.yaml

images:
  - name: garbo
    newName: flux-system:garbo-dev
