apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garbo

resources:
  - worker.yaml
  - api.yaml
  - ingress.yaml
  - nlm-ingestor.yaml
  - service.yaml

images:
  - name: ghcr.io/klimatbyran/garbo
    newName: ghcr.io/klimatbyran/garbo # {"$imagepolicy": "flux-system:garbo-dev:name"}
    newTag: 3.1.18 # {"$imagepolicy": "flux-system:garbo-dev:tag"}
