---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: garbo
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "15.5.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    auth:
      username: postgres
      password: postgres-password
      database: metabase
    primary:
      persistence:
        enabled: true
        size: 8Gi
