apiVersion: apps/v1
kind: Deployment
metadata:
  name: garbo
  namespace: garbo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garbo
  template:
    metadata:
      labels:
        app: garbo
    spec:
      containers:
        - image: ghcr.io/klimatbyran/garbo:3.4.13 # {"$imagepolicy": "flux-system:garbo"}
          resources: {}
          name: garbo
          ports:
            - containerPort: 3000
          env:
            - name: DISCORD_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_APPLICATION_ID
            - name: DISCORD_SERVER_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_SERVER_ID
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_TOKEN
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: OPENAI_API_KEY
            - name: OPENAI_ORG_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: OPENAI_ORG_ID
            - name: API_TOKENS
              valueFrom:
                secretKeyRef:
                  name: env
                  key: API_TOKENS
            - name: API_BASE_URL
              value: http://garbo/api
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql:5432/garbo
            - name: CHROMA_HOST
              value: http://chromadb:8000
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          imagePullPolicy: Always
