apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-pipeline
  namespace: data-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-pipeline
  template:
    metadata:
      labels:
        app: data-pipeline
    spec:
      containers:
        - image: ghcr.io/klimatbyran/data-pipeline:1.1.24 # {"$imagepolicy": "flux-system:data-pipeline"}
          resources: {}
          name: data-pipeline
          ports:
            - containerPort: 3000
          env:
            - name: DISCORD_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_APPLICATION_ID
            - name: DISCORD_SERVER_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_SERVER_ID
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_TOKEN
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: OPENAI_API_KEY
            - name: OPENAI_ORG_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: OPENAI_ORG_ID
            - name: ELASTIC_NODE_URL
              valueFrom:
                secretKeyRef:
                  name: env
                  key: ELASTIC_NODE_URL
            - name: ELASTIC_INDEX_NAME
              valueFrom:
                secretKeyRef:
                  name: env
                  key: ELASTIC_INDEX_NAME
            # - name: CHROMA_TOKEN
            #   valueFrom:
            #     secretKeyRef:
            #       name: chromadb-auth
            #       key: token
            - name: CHROMA_HOST
              value: http://chromadb:8000
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
