apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
  namespace: gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      containers:
        - image: gotenberg/gotenberg
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
          name: gotenberg
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: gotenberg
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: gotenberg
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotenberg
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - gotenberg.klimatkollen.se
      secretName: gotenberg-klimatkollen-se-tls

  rules:
    - host: gotenberg.klimatkollen.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gotenberg
                port:
                  number: 3000
