---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: data-pipeline
  namespace: flux-system
spec:
  image: ghcr.io/klimatbyran/data-pipeline
  interval: 30s
  provider: generic
