---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: data-pipeline
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: data-pipeline
  policy:
    semver:
      range: "x.x.x"
