apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: ghcr.io/klimatbyran/garbo:3.1.18 # {"$imagepolicy": "flux-system:garbo-dev"}
          command: ['npm', 'run', 'migrate']
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql:5432/garbo
