apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garbo-stage
resources:
  - ../../base
patches:
  - path: ingress-patch.yaml
  - path: worker-patch.yaml
  - path: managed-cert-patch.yaml
images:
  - name: ghcr.io/klimatbyran/garbo
    newTag: '*' # {"$imagepolicy": "flux-system:garbo-stage:tag"}
